[project]
name = "xmtl-factory"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "jinja2>=3.1.6",
    "pypdf>=6.7.1",
    "pyyaml>=6.0.3",
    "rich>=14.3.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
]
